from construct import GreedyBytes, Struct, Switch, this

from pyceos.types import E16_7, F8_3, F16_7, AsciiInt, AsciiString, Spare

from .sensor_specific import SensorSpecificAlos

DataSetSummaryRecord = Struct(
    "sequence_number" / AsciiInt(4),
    "sar_chan" / AsciiInt(4),
    "product_id" / AsciiString(16),
    "scene_des" / AsciiString(32),
    "inp_sctim" / AsciiString(32),
    "asc_des" / AsciiString(16),
    "pro_lat" / F16_7,
    "pro_long" / F16_7,
    "pro_head" / F16_7,
    "ellip_des" / AsciiString(16),
    "ellip_maj" / F16_7,
    "ellip_min" / F16_7,
    "earth_mass" / F16_7,
    "grav_const" / F16_7,
    "ellip_j" / F16_7[3],
    # In mapready the following 48 bytes can also be partitioned differently
    # ----------
    Spare(16),
    "terrain_h" / F16_7,
    "sc_lin" / AsciiInt(8),
    "sc_pix" / AsciiInt(8),
    # ----------
    "scene_len" / F16_7,
    "scene_wid" / F16_7,
    Spare(16),
    "nchn" / AsciiInt(4),
    Spare(4),
    "mission_id" / AsciiString(16),
    "sensor_id" / AsciiString(32),
    "revolution" / AsciiInt(8),
    "plat_lat" / F8_3,
    "plat_long" / F8_3,
    "plat_head_scene" / F8_3,
    "clock_ang" / F8_3,
    "incident_ang" / F8_3,
    "frequency" / F8_3,
    "wave_length" / F16_7,
    "motion_comp" / AsciiString(2),
    "pulse_code" / AsciiString(16),
    "ampl_coef" / E16_7[5],
    "phase_coef" / E16_7[5],
    "chirp_ext_ind" / AsciiInt(8),
    Spare(8),
    "rng_samp_rate" / F16_7,
    "rng_gate" / F16_7,
    "rng_length" / F16_7,
    "baseband_f" / AsciiString(4),
    "rngcmp_f" / AsciiString(4),
    "gn_polar" / F16_7,
    "gn_cross" / F16_7,
    "chn_bits" / AsciiInt(8),
    "quant_desc" / AsciiString(12),
    "i_bias" / F16_7,
    "q_bias" / F16_7,
    "iq_ratio" / F16_7,
    "spare_dss_7" / F16_7,
    "spare_dss_8" / F16_7,
    "ele_sight" / F16_7,
    "mech_sight" / F16_7,
    "echo_track" / AsciiString(4),
    "prf" / F16_7,
    "elev_beam" / F16_7,
    "azi_beam" / F16_7,
    "sat_bintim" / AsciiInt(16),
    "sat_clktim" / AsciiString(32),
    "sat_clkinc" / AsciiInt(16),
    "fac_id" / AsciiString(16),
    "sys_id" / AsciiString(8),
    "ver_id" / AsciiString(8),
    "fac_code" / AsciiString(16),
    "lev_code" / AsciiString(16),
    "product_type" / AsciiString(32),
    "algor_id" / AsciiString(32),
    "n_azilok" / F16_7,
    "n_rnglok" / F16_7,
    "bnd_azilok" / F16_7,
    "bnd_rnglok" / F16_7,
    "bnd_azi" / F16_7,
    "bnd_rng" / F16_7,
    "azi_weight" / AsciiString(32, leftpad=True),
    "rng_weight" / AsciiString(32, leftpad=True),
    "data_inpsrc" / AsciiString(16),
    "rng_res" / F16_7,
    "azi_res" / F16_7,
    "radi_stretch" / F16_7[2],
    "alt_dopcen" / F16_7[3],
    Spare(16),
    "crt_dopcen" / F16_7[3],
    "time_dir_pix" / AsciiString(8),
    "time_dir_lin" / AsciiString(8),
    "alt_rate" / F16_7[3],
    Spare(16),
    "crt_rate" / F16_7[3],
    Spare(16),
    "line_cont" / AsciiString(8),
    "clutterlock_flg" / AsciiString(4),
    "auto_focus" / AsciiString(4),
    "line_spacing" / F16_7,
    "pixel_spacing" / F16_7,
    "rngcmp_desg" / AsciiString(16),
    "dopcen_const" / F16_7,
    "dopcen_lin" / F16_7,
    "sensor_specific" / Switch(
        this.sensor_id[:4],
        {
            "ALOS": SensorSpecificAlos,
        },
        default=GreedyBytes
    ),
)
