from enum import Enum


class RecordType(Enum):
    DATA_SET_SUMMARY = 10
    SCENE_HEADER = 18
    MAP_PROJECTION = 20
    PLATFORM_POSITION = 30
    MAP_PROJECTION_ALOS = 36
    ATTITUDE = 40
    RADIOMETRIC = 50    # TODO(reweeden): Record can be different for ALOS, but with same code
    RADIOMETRIC_COMPENSATION = 51
    DATA_QUALITY = 60
    DATA_HISTOGRAM = 70
    RANGE_SPECTRA = 80
    PROCESSING_PARAMETER = 120
    IMAGERY_OPTIONS = 192
    TRAILER_FILE_DESCRIPTOR = 193
    FACILITY_RELATED = 200
    ASF_FACILITY_RELATED = 210
    ESA_FACILITY_RELATED = 220
    JAXA_FACILITY_RELATED = 230
    FILE_DESCRIPTOR = 300
